name: minimap2_align
description: |
  Align reads to a reference sequence with minimap2 and sort/index the resulting BAM with samtools
keywords:
  - "alignment"
  - "minimap2"
  - "samtools"
tools:
  - minimap2:
      description: Versatile pairwise aligner for genomic and spliced nucleotide sequences
      homepage: https://github.com/lh3/minimap2
      doi: "10.1093/bioinformatics/bty191"
      licence:
        - "MIT"
  - samtools:
      description: Suite of programs for interacting with high-throughput sequencing data
      homepage: http://www.htslib.org
      documentation: http://www.htslib.org/doc/samtools.html
      doi: "10.1093/gigascience/giab008"
      licence:
        - "MIT"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: List of input FASTQ files
  - - reference:
        type: file
        description: Reference
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: BAM alignment file
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bai":
          type: file
          description: BAM index file
  coverage:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.txt":
          type: file
          description: Per-contig/per-sample coverage file
  versions:
    - - "versions.yml":
          type: file
          description: File containing software versions
authors:
  - "@ajodeh-juma"
maintainers:
  - "@ajodeh-juma"
