name: samtools_sort
description: |
  Sort a BAM file by coordinate with samtools sort
keywords:
  - "sorting"
  - "samtools"
  - "bam"
tools:
  - samtools:
      description: Suite of programs for interacting with high-throughput sequencing data
      homepage: http://www.htslib.org
      documentation: http://www.htslib.org/doc/samtools.html
      doi: "10.1093/gigascience/giab008"
      licence:
        - "MIT"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: BAM alignment file
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.sorted.bam":
          type: file
          description: BAM alignment file
  versions:
    - - "versions.yml":
          type: file
          description: File containing software versions
authors:
  - "@ajodeh-juma"
maintainers:
  - "@ajodeh-juma"
